---
- hosts: mail
  become: yes
  vars_files:
    - vault.yml
  tasks:

  - include_tasks: tasks/00-rpms.yml
    tags:
      - rpms

  - include_tasks: tasks/01-services.yml
    tags:
      - services

  - include_tasks: tasks/02-firewall.yml
    tags:
      - firewall

  - include_tasks: tasks/03-users.yml
    tags:
      - user
  
  - import_tasks: tasks/04-mysql.yml
    tags:
      - mysql






