---
- hosts: mail8
  become: yes
  handlers:
    - include: handlers/main.yml
  vars_files:
    - vault.yml
  tasks:

  - import_tasks: tasks/00-rpms.yml
    tags:
      - rpms

  - import_tasks: tasks/01-services.yml
    tags:
      - services

  - import_tasks: tasks/02-firewall.yml
    tags:
      - firewall
  
        #  - import_tasks: tasks/git_handling.yml
        #    vars:
        #      - stage: '1'
        #    tags:
        #      - git

  - import_tasks: tasks/03-users.yml
    tags:
      - user
  
  - import_tasks: tasks/04-mysql.yml
    tags:
      - mysql

  - import_tasks: tasks/05-postfix.yml
    tags:
      - postfix

  - import_tasks: tasks/07-postfixadmin.yml
    tags:
      - postfixadmin





