---

- name: rspamd repo
  yum_repository:
    name: rspamd
    description: rspamd
    #baseurl: http://rspamd.com/rpm-stable/centos-7/x86_64/
    baseurl: http://rspamd.com/rpm-stable/centos-8/x86_64/
    gpgcheck: yes
    gpgkey: https://rspamd.com/rpm-stable/gpg.key
    enabled: yes

- name: install epel
  yum:
    name: epel-release
    state: latest

- name: remi for roundcube
  yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: present

- name: enable remi repo
  shell: yum-config-manager --enable remi
  changed_when: False

- name: set module stream for php
  shell: yum module enable php:remi-7.4 -y
  changed_when: False
  args:
    warn: no

- name: install packages
  yum:
    name:
      - python3
      - postfix
      - rspamd
      - dovecot
      - httpd
      - php
      - php-imap
      - php-mysqlnd
      - roundcubemail
      - mariadb-server
      - dovecot-mysql
      ##- MySQL-python
      - python3-PyMySQL
      - python3-policycoreutils
      - git
    state: latest

...
