---
- name: set running daemons
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: 
    - httpd
      #    - postfix
    - dovecot
    - mariadb
    - rspamd
    #- redis
...
